section_purger.settings.*:
  type: config_entity
  label: 'Section Purger'
  mapping:

    #
    # Instance metadata:
    #
    id:
      type: string
      translatable: false
    name:
      type: string
      translatable: false
    invalidationtype:
      type: string
      translatable: false

    #
    # Primary request information:
    #
    hostname:
      type: string
      translatable: false
    sitename:
      type: string
      translatable: false
    port:
      type: integer
      translatable: false
    path:
      type: string
      translatable: false
    account:
      type: integer
      translatable: false
    application:
      type: integer
      translatable: false
    environmentname:
      type: string
      translatable: false
    username:
      type: string
      translatable: false
    password:
      type: key_select
      translatable: false
    requestMethod:
      type: string
      translatable: false
    scheme:
      type: string
      translatable: false
    verify:
      type: string
      translatable: false
    varnishname:
      type: string
      translatable: false

    #
    # Request headers (outbound):
    #
    headers:
      type: sequence
      translatable: false
      sequence:
        type: section_purger_header

    #
    # Body (request payload):
    #
    body:
      type: text
      translatable: false
    bodyContentType:
      type: string
      translatable: false

    #
    # Performance settings:
    #
    runtimeMeasurement:
      type: boolean
      translatable: false
    timeout:
      type: float
      translatable: false
    connectTimeout:
      type: float
      translatable: false
    cooldownTime:
      type: float
      translatable: false
    maxRequests:
      type: integer
      translatable: false

    #
    # Success resolution:
    #
    httpErrors:
      type: boolean
      translatable: false
